name: Ubuntu

on: [push, workflow_dispatch]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - name: Download Ngrok
      run: brew install ngrok/ngrok/ngrok
    - name: Auth
      run: ngrok config add-authtoken $NGROK_AUTH_TOKEN
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
    - name: Enable RDP
      run: sudo /System/Library/CoreServices/RemoteManagement/ARDAgent.app/Contents/Resources/kickstart -activate
    - run: dscl . -create /Users/amon
    - run: dscl . -create /Users/amon UserShell /bin/bash
    - run: dscl . -create /Users/amon RealName "AMON" 
    - run: dscl . -create /Users/amon UniqueID "510"
    - run: dscl . -create /Users/amon PrimaryGroupID 20
    - run: dscl . -create /Users/amon NFSHomeDirectory /Users/joeadmin
    - run: dscl . -passwd /Users/amon amon1234 
    - run: dscl . -append /Groups/admin GroupMembership amon
    - name: Create Tunnel
      run: ngrok tcp 3389
